const toolsImgData=[
    {id:1,name:"Angular",defaultImgUrl:'/images/admin/tools/Angular _ Gray.svg',selectedImgUrl:"/images/admin/tools/Angular _ Blue.svg"},
      {id:2,name:"Atlasian",defaultImgUrl:"/images/admin/tools/Atlasian _ Gray.svg",selectedImgUrl:"/images/admin/tools/Atlasian _ Blue.svg"},
     {id:3,name:"AWS",defaultImgUrl:"/images/admin/tools/AWS _ Gray.svg",selectedImgUrl:"/images/admin/tools/AWS _ Blue.svg"},
     {id:4,name:"Azure",defaultImgUrl:"/images/admin/tools/Azure _ Gray.svg",selectedImgUrl:"/images/admin/tools/Azure _ Blue.svg"},
    {id:5,name:"C#",defaultImgUrl:"/images/admin/tools/C-Sharp _ Gray.svg",selectedImgUrl:"/images/admin/tools/C-Sharp _ Blue.svg"},
    {id:6,name:"C++",defaultImgUrl:"/images/admin/tools/C++ _ Gray.svg", selectedImgUrl:"/images/admin/tools/C++ _ Blue.svg"},
    {id:7,name:"CSS",defaultImgUrl:"/images/admin/tools/CSS _ Gray-1.svg",selectedImgUrl:"/images/admin/tools/CSS _ Blue.svg"},
    {id:8,name:"Django",defaultImgUrl:"/images/admin/tools/Django _ Gray.svg",selectedImgUrl:"/images/admin/tools/Django _ Blue.svg"},
    {id:9,name:"Docker",defaultImgUrl:"/images/admin/tools/Docker _ Gray.svg",selectedImgUrl:"/images/admin/tools/Docker _ Blue.svg"},
    {id:10,name:"Sigma",defaultImgUrl:"/images/admin/tools/Figma _ Gray.svg",selectedImgUrl:"/images/admin/tools/Figma _ Blue.svg"},
    {id:11,name:"Git",defaultImgUrl:"/images/admin/tools/Git _ Gray.svg",selectedImgUrl:"/images/admin/tools/Git _ Blue.svg"},
   {id:12,name:"HTML",defaultImgUrl:'/images/admin/tools/HTML _ Gray-1.svg',selectedImgUrl:"/images/admin/tools/HTML _ Blue.svg"},
    {id:13,name:"Java",defaultImgUrl:'/images/admin/tools/Java _ Gray.svg',selectedImgUrl:"/images/admin/tools/Java _ Blue.svg"},
    {id:14,name:"Jira",defaultImgUrl:'/images/admin/tools/Jira _ Gray.svg',selectedImgUrl:"/images/admin/tools/Jira _ Blue.svg"},
    {id:15,name:"JS",defaultImgUrl:'/images/admin/tools/JS _ Gray.svg',selectedImgUrl:"/images/admin/tools/JS _ Blue.svg"},
    {id:16,name:"Junit",defaultImgUrl:'/images/admin/tools/Junit _ Gray.svg',selectedImgUrl:"/images/admin/tools/Junit _ Blue.svg"},
    {id:17,name:"MongoDB",defaultImgUrl:'/images/admin/tools/MongoDB _ Gray.svg',selectedImgUrl:"/images/admin/tools/MongoDB _ Blue.svg"},
    {id:18,name:"MySQL",defaultImgUrl:'/images/admin/tools/MySQL _ Gray.svg',selectedImgUrl:"/images/admin/tools/MySQL _ Blue.svg"},
    {id:19,name:"Node JS",defaultImgUrl:'/images/admin/tools/Node JS _ Gray.svg',selectedImgUrl:"/images/admin/tools/Node JS _ Blue.svg"},
    {id:20,name:"PHP",defaultImgUrl:'/images/admin/tools/PHP _ Gray.svg',selectedImgUrl:"/images/admin/tools/PHP _ Blue.svg"},
    {id:21,name:"Pycharm",defaultImgUrl:'/images/admin/tools/Pycharm _ Gray.svg',selectedImgUrl:"/images/admin/tools/Pycharm _ Blue.svg"},
    {id:22,name:"Python",defaultImgUrl:'/images/admin/tools/Python _ Gray.svg',selectedImgUrl:"/images/admin/tools/Python _ Blue.svg"},
    {id:23,name:"React",defaultImgUrl:'/images/admin/tools/React _ Gray.svg',selectedImgUrl:"/images/admin/tools/React _ Blue.svg"},
    {id:24,name:"Scrum",defaultImgUrl:'/images/admin/tools/Scrum _ Gray.svg',selectedImgUrl:"/images/admin/tools/Scrum _ Blue.svg"},
    {id:25,name:"Selenium",defaultImgUrl:'/images/admin/tools/Selenium _ Gray.svg',selectedImgUrl:"/images/admin/tools/Selenium _ Blue.svg"},
    {id:26,name:"Slack",defaultImgUrl:'/images/admin/tools/Slack _ Gray.svg',selectedImgUrl:"/images/admin/tools/Slack _ Blue.svg"},
    {id:27,name:"Spring",defaultImgUrl:'/images/admin/tools/Spring _ Gray.svg',selectedImgUrl:"/images/admin/tools/Spring _ Blue.svg"},
    {id:28,name:"SQL Server",defaultImgUrl:'/images/admin/tools/SQL Server _ Gray.svg',selectedImgUrl:"/images/admin/tools/SQL Server _ Blue.svg"},
    {id:29,name:"Trello",defaultImgUrl:'/images/admin/tools/Trello _ Gray.svg',selectedImgUrl:"/images/admin/tools/Trello _ Blue.svg"},
    {id:30,name:"Visual Studio",defaultImgUrl:'/images/admin/tools/Visual Studio _ Gray.svg',selectedImgUrl:"/images/admin/tools/Visual Studio _ Blue.svg"}
    ]

    module.exports={toolsImgData}